export const AuthLogin = (_req, res, _next) => {
    try {
    }
    catch (error) {
        res.status(500).send(error.messaje);
    }
};
